url: "https://lichess.org/"
token: ""

engine:
  name: "chester"
  cmd: chester
  dir: "/lichess-bot"
  protocol: uci
  debug: true

challenge:
  accept_bot: true
  accept_human: true

  variants:
    - standard

  time_controls:
    - bullet
    - blitz
    - rapid
  
  modes:
    - rated
    - casual

matchmaking:
  allow_matchmaking: true
  allow_during_games: false
  challenge_variant: "standard"
  challenge_timeout: 5

  challenge_initial_time:
    - 300

  challenge_increment:
    - 3

  challenge_mode: "rated"