url: "https://lichess.org/"
token: ""

engine:
  name: "chester"
  cmd: chester
  dir: "/lichess-bot"
  protocol: uci

challenge:
  accept_bot: true
  accept_human: true

  variants:
    - standard

  time_controls:
    - bullet
    - blitz
    - rapid
  
  modes:
    - rated
    - casual